### ISSUE TITLE
Cannot log in, update or rebuild forces new secret in twp.conf?

### ISSUE THREAD

**Issue by jxsl13** [Tardo/twp#43]
Cannot log in, update or rebuild forces new secret in twp.conf?
After I updated, if I remember correctly, I rebuilt the container with docker-compose and updated the source with git pull inside the container. Does any of this cause the secret to be updated in the container's twp.conf ?

**Comment by Tardo** [comment]
Rebuild container = Use DOCKERFILE = COPY twp.conf to /app folder = Yes, lost secret :/
For update i only do the pull inside docker.

perhaps is best use ENTRYPOINT and apply some logic instead hard copy in dockerfile... :/

**Comment by jxsl13** [comment]
good to know (Y)

**Comment by jxsl13** [comment]
is it possible to renew my admin tw from within the docker container?
or do I need to reinstall  twp?

**Comment by Tardo** [comment]
Update twp in your docker, restart it... and enter in '/restore_admin' ;)

**Comment by jxsl13** [comment]
is that a URL or a folder?

**Comment by Tardo** [comment]
url

**Comment by jxsl13** [comment]
nice nice :D 👍

**Comment by jxsl13** [comment]
maybe not as easy as expected :/ causing internal server error 500

**Comment by Tardo** [comment]
can you see the log?

**Comment by jxsl13** [comment]
maybe it is needed to recreate the sqlite db?

```
Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./webcontroller/public.py", line 217, in login
    if dbuser.count() > 0:
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3089, in count
    return self.from_self(col).scalar()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2843, in scalar
    ret = self.one()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2814, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)   
 ret = list(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such column: user.is_demo [SQL: u'SELECT count(*) AS count_1 \nFROM (SELECT user.id AS user_id, user.create_date AS user_create_d$

```

**Comment by Tardo** [comment]
?¿?? strange error.. using old database.. perhaps a mistake in rebuild with "rm -r /app" instruction... need improve docker-compose manifest :S  
The manual solution is... stop docker, open /var/lib/docker/volumes/_data/twp.db and add the column "is_demo" to "User" table... :/

**Comment by jxsl13** [comment]
yep, worked fine :)
